language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
services:
  - mongodb
script: make test-cov
before_script:
  - npm install mongodb
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
